# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-29 04:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rules',
            name='collection',
            field=models.CharField(default='orders', max_length=255),
            preserve_default=False,
        ),
    ]
