# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_auto_20170929_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriggeredRules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=255)),
                ('data', models.TextField()),
            ],
        ),
    ]
