# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_triggeredrules'),
    ]

    operations = [
        migrations.RenameField(
            model_name='triggeredrules',
            old_name='data_id',
            new_name='rule_key',
        ),
    ]
