# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_auto_20171010_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggeredrules',
            name='email',
            field=models.EmailField(default='test@mail.com', max_length=255),
            preserve_default=False,
        ),
    ]
