# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_triggeredrules_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecutionSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(max_length=255)),
                ('rule_summary', models.TextField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
